# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

target 'schedules' do

pod "CSStickyHeaderFlowLayout"
pod "OAStackView"
pod "GoogleMaps"
pod "Parse"

end

target 'schedulesTests' do

end

